In [1]:
import pandas as pd 
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
dataset=pd.read_csv('SaratogaHouses.csv')

In [13]:
x=dataset['livingArea'].values
y=dataset['price'].values
dataset.head()

Unnamed: 0   price  lotSize  age  landValue  livingArea  pctCollege  \
0           1  132500     0.09   42      50000         906          35   
1           2  181115     0.92    0      22300        1953          51   
2           3  109000     0.19  133       7300        1944          51   
3           4  155000     0.41   13      18700        1944          51   
4           5   86060     0.11    0      15000         840          51   

   bedrooms  fireplaces  bathrooms  rooms          heating      fuel  \
0         2           1        1.0      5         electric  electric   
1         3           0        2.5      6  hot water/steam       gas   
2         4           1        1.0      8  hot water/steam       gas   
3         3           1        1.5      5          hot air       gas   
4         2           0        1.0      3          hot air       gas   

               sewer waterfront newConstruction centralAir  
0             septic         No              No         No  
1             septic         No              No         No  
2  public/commercial         No              No         No  
3             septic         No              No         No  
4  public/commercial         No             Yes        Yes

In [14]:
dataset.shape

(1728, 17)

In [15]:
print(x.shape)

(1728,)


In [18]:
x=x.reshape(-1,1)

In [21]:
x[0:10]

array([[ 906],
       [1953],
       [1944],
       [1944],
       [ 840],
       [1152],
       [2752],
       [1662],
       [1632],
       [1416]], dtype=int64)

In [23]:
regL=LinearRegression()
regL.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
y_pred=regL.predict(x)

In [26]:
print(y[0:10],"\n")
print(y_pred[0:10],"\n")


[132500 181115 109000 155000  86060 120000 153000 170000  90000 122900] 

[115928.4169181  234367.71823171 233349.61535509 233349.61535509
 108462.32915621 143756.56221241 324752.62916731 201449.05855429
 198055.38229888 173620.91325997] 



In [27]:
regL.predict([[906]])

array([115928.4169181])

In [30]:
regL.coef_

array([113.12254185])

In [31]:
regL.intercept_

13439.394004889502

In [32]:
from sklearn.model_selection import train_test_split

In [48]:
x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [49]:
print(x_train.shape,x_test.shape,y_train.shape, y_test.shape)

(1382, 1) (346, 1) (1382,) (346,)


In [50]:
regL2=LinearRegression()
regL2.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [51]:
y_pred=regL2.predict(x_test)

In [52]:
from sklearn.metrics import mean_squared_error

In [53]:
mse=mean_squared_error(y_test,y_pred)

In [54]:
rmse=np.sqrt(mse)

In [55]:
mse, rmse

(5424698823.672778, 73652.55476677492)